##  ziye 
## github地址 https://github.com/6Svip120apk69
## TG频道地址  https://t.me/ziyescript
## TG交流群   https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
## boxjs链接  https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json


## 新建一个库，此文件路径为 .github/workflows/ziye-sync.yml 打开教程链接 https://www.jianshu.com/p/bb82b3ad1d11 ，申请PAT（勾选时尽量全部勾选 ），找到Settings------secrets------New repository secret------name填写PAT    value填写PAT的值        

## 点击 Actions  手动运行或者等待定时运行即可自动生成分支 ZIYE 且自动同步文件至此

## 其他作者库同理  替换如下    
 
## 作者名         6Svip120apk69  
## 作者库名       gitee_q8qsTAUA_cThxc1RBVUE     
## 作者分支名     main     
## 同步分支名     ZIYE   （可自定义 ）




name: ziye-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git"
          source_branch: "main"
          destination_branch: "ZIYE"
          github_token: ${{ secrets.PAT }}
